imports:
    - php

filter:
    excluded_paths: 
        - 'tests/*'
        - 'bin/*'
        - 'tools/*'
        - '*/vendor/*'
        - 'build/*'
        - 'migrations/*'
build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.1
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -
                # command: "composer phpunit"
                command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "build/coverage.xml"
                    format: "clover"